import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Product } from '../data/Product';

export default function Home() {
  console.log(Product);
  return (
    <div className={styles.container}>
      <Head>
        <title>React Lunch-n-Learn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>React Lunch-n-Learn</h1>
      </main>
    </div>
  )
}
